# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "netdata/netdata"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Netdata"
  org.opencontainers.image.description: "Netdata https://www.netdata.cloud/ Monitor everything in real time. For free"
  org.opencontainers.image.source: "https://github.com/gcurteanu/netdata-homeassistant-addon"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.version: "2.1.2"
